* 0bl-mode

This mode provides the ability to have several layouts saved and then you can
easily switch between your saved layouts. When you first load the mode, you will
get a "default" layout named "default".

Then you have the ability to create new layouts ~C-c C-l C-c~ and name them.
There you can set up your layout as you want it, open buffers, do stuff.

And when you have more than one layout, you can switch between the layouts you
have active with ~C-c C-l C-b~.

You can also kill the layout that you're currently visiting with ~C-c C-l C-k~.

*Note:* I'm sorry for my bad elisp. I don't think it's that bad, but this is
basicly the first thing I've ever built in elisp more than my .emacs-file, which
depends alot on stackoverflow and other sources on internet.

** TODO
 - Add name of current layout to the mode-line
 - Tab completions of layouts available when switching layout
 - Kill other layouts than the one you're visiting, also with tab-completions

** Why the name?
0b is just a prefix I use for things because I have the domain 0b.se, and
lowercase L as in "Layout", that's it basicly.
